### PR TITLE
Adding Reason Entity Archiver Script/Class

### PR DESCRIPTION
**Pull request by mischler**
Adding Reason Entity Archiver Script/Class to Reason; maintenance
script to review and delete outdated content.

### CODE REVIEW

**Comment by mischler** [comment]
I just noticed that this request is still around. Are there any concerns that needed to be addressed with this? @slylth

**Comment by slylth** [comment]
Not that I know of, just didn't have time to test before the last release. Will make sure to get it into 4.7.

**Comment by mischler** [comment]
Makes sense to me.  Just let me know if you need anything from me about it.

**Comment by slylth** [comment]
Will do. Thanks.

**Pull request merged**
