### PR TITLE
Carl pull

### PR DESCRIPTION
**Pull request by DookTibsCarl**
Here's Carleton's changes for the 4.6 release

### CODE REVIEW

**Comment by slylth** [comment]
@mryand Do you think you could walk through this with @DookTibsCarl for a code review? There's a good deal here and I think you've probably tested them fairly well at Carleton.

**Comment by natepixel** [comment]
I recommend taking the profile commits out of this pull request - the module as included here is not functional in a base reason install. I've done a lot of additional work to make profiles general and functional in the reason core (https://github.com/natepixel/reason_package/tree/FEATURE-profiles) and expect to be able to release profiles for Reason 4.7. That release has a lot of changes from the profiles code here, including some file location changes, and I think it would be better to release all of it in 4.7 when it is functional and easy to deploy.

**Comment by slylth** [comment]
@mheiman Should the catalog commits be in this version or hold them for 4.7?

**Comment by slylth** [comment]
[Merged into branch 4.6](https://github.com/carleton/reason_package/commit/19f3007a92ed6f6378bf3f58e8fa978feee612e7). Didn't auto-close because I left out the profiles-related code which will be included in 4.7.

**Comment by mheiman** [comment]
We can leave it out — it’s only useful at this point if someone wants to start experimenting with it before the import functions are fully generalized.

		mfh

**Pull request closed without merging**
