### PR TITLE
Tinymce assets

### PR DESCRIPTION
**Pull request by brifishjones**
This finishes up work on choosing an existing asset from an inserted/edited link in TinyMCE.

### CODE REVIEW

**Comment by slylth** [comment]
@mryand @tabitagreen @brifishjones This pull also includes removal of the indent/outdent buttons from the default layout. Is this something we want in the core? Might make more sense to have this as a TinyMCE option in the site setup. Or use this as the default and offer an option to include the buttons.

**Comment by mryand** [comment]
I agree, that should be an option but not baked in. 

Matt 


----- Original Message -----

**Comment by tabitagreen** [comment]
Yes to having it as a setting.

On Fri, Feb 27, 2015 at 4:21 PM, Matt Ryan <notifications@github.com> wrote:

> I agree, that should be an option but not baked in.
>
> Matt
>
>
> ----- Original Message -----
>
> From: "Steve Smith" <notifications@github.com>
> To: "carleton/reason_package" <reason_package@noreply.github.com>
> Cc: "Matt Ryan" <mryan@carleton.edu>
> Sent: Friday, February 27, 2015 3:33:11 PM
> Subject: Re: [reason_package] Tinymce assets (#107)
>
>
>
> @mryand @tabitagreen @brifishjones This pull also includes removal of the
> indent/outdent buttons from the default layout. Is this something we want
> in the core? Might make more sense to have this as a TinyMCE option in the
> site setup. Or use this as the default and offer an option to include the
> buttons.
>
> —
> Reply to this email directly or view it on GitHub .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carleton/reason_package/pull/107#issuecomment-76483529>
> .
>



-- 
*Tabita Green*
Director of Web Content
Luther College <http://www.luther.edu/>
Email: greeta02@luther.edu
Office: 563-387-1902
Cell: 563-387-7663
Facebook <https://www.facebook.com/luthercollege> | Google+
<https://plus.google.com/106145735238161370551/posts> | Twitter
<https://twitter.com/luthercollege> | YouTube
<http://www.youtube.com/user/luthercollegemedia> | LinkedIn
<http://www.linkedin.com/in/tabitagreen>

Ask me about Reason CMS <http://reasoncms.org>, built by and for Higher Ed.

**Comment by slylth** [comment]
@tabitagreen @mryand After a closer look, Loki2 only let you indent/outdent on lists. So this change would be ok. There is a setting in tinymce to allow indenting list but only via the tab key. If the indent/outdent buttons are present, all content is available for indent/outdent. So, I think we should remove the buttons and turn on the tab setting. I'd guess that most users would be used to this type of behavior. Thoughts?

**Comment by tabitagreen** [comment]
Agree.

On Wed, Mar 4, 2015 at 10:59 AM, Steve Smith <notifications@github.com>
wrote:

> @tabitagreen <https://github.com/tabitagreen> @mryand
> <https://github.com/mryand> After a closer look, Loki2 only let you
> indent/outdent on lists. So this change would be ok. There is a setting in
> tinymce to allow indenting list but only via the tab key. If the
> indent/outdent buttons are present, all content is available for
> indent/outdent. So, I think we should remove the buttons and turn on the
> tab setting. I'd guess that most users would be used to this type of
> behavior. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carleton/reason_package/pull/107#issuecomment-77197814>
> .
>



-- 
*Tabita Green*
Director of Web Content
Luther College <http://www.luther.edu/>
Email: greeta02@luther.edu
Office: 563-387-1902
Cell: 563-387-7663
Facebook <https://www.facebook.com/luthercollege> | Google+
<https://plus.google.com/106145735238161370551/posts> | Twitter
<https://twitter.com/luthercollege> | YouTube
<http://www.youtube.com/user/luthercollegemedia> | LinkedIn
<http://www.linkedin.com/in/tabitagreen>

Ask me about Reason CMS <http://reasoncms.org>, built by and for Higher Ed.

**Comment by mryand** [comment]
Is unindent via shift-tab?

**Comment by slylth** [comment]
Yes.

**Pull request merged**
