### PR TITLE
patterns for title tags

### PR DESCRIPTION
**Pull request by quinn**
Currently this uses 3 new fields on Site. defaults can be set in settings.php. Fields available are:

~~~ php
public $tags = array('organization_name', 'minisite_name', 'item_name', 'page_title');
~~~

### CODE REVIEW

**Comment by slylth** [comment]
@quinn Can you pull that ldap_escape code, please? thanks.
@mryand Are all your changes here?

**Comment by quinn** [comment]
@slylth do you mean remove it from this PR?

**Comment by slylth** [comment]
@quinn Yes. I merged it in from #78. You mentioned earlier that you could pull it out.

**Comment by quinn** [comment]
is it ok if i rebase to remove? or is it preferable if i revert (i.e. history rewrite vs no rewrite)

**Comment by slylth** [comment]
Fine by me for the rebase.

**Comment by slylth** [comment]
If you can't pull it out easily, it's no problem. Just let me know.

**Comment by slylth** [comment]
@quinn Don't worry about pulling out.

**Comment by quinn** [comment]
@slylth sorry for the delay, i can take care of this now.. it looks like there are conflicts as well. I think it makes the most sense to just rebase it onto whatever branch you need it on and resolve the conflicts in the process. Where should it go?

**Comment by quinn** [comment]
develop?

**Comment by slylth** [comment]
Really. No worries. I'm merging it now and fixing conflicts. Cheers.

**Comment by quinn** [comment]
ok, thanks

**Pull request merged**
