### PR TITLE
dev work integration

### PR DESCRIPTION
**Pull request by quinn**
Hey all, I've integrated all of the work I've done so far into one branch, this one could be merged (which would close the existing PRs) or they can be merged individually.

### CODE REVIEW

**Comment by slylth** [comment]
Are the changes to to settings/dbs.xml, settings/reason_settings.php, and settings/error_handler_settings.php for the docker deployment?

**Comment by slylth** [comment]
And if so, do you know if they break the other deployment scripts (both the install script and the Vagrant/Ansible deployment)? I can test, but am just wondering if you know off the top of your head.

**Comment by slylth** [comment]
@quinn Any thoughts?

**Comment by quinn** [comment]
no, those were committed accidentally by nathan or myself at some point. Really, those files should be gitignored right? and have the "default" versions appended with ".example" .e.g. dbs.xml.example. Does that make sense? Either way I can revert the changes to those files.

**Comment by slylth** [comment]
Yep. Makes sense. Could you revert the changes. Thanks.

**Comment by quinn** [comment]
@slylth ok, those changes should be reverted. those files should no longer be part of the diff.

**Comment by quinn** [comment]
ok, there are still changes in reason_settings.php from what i can tell. I'm going to try to fix that now.

**Comment by quinn** [comment]
ok, should be fixed now.

**Pull request merged**
